  - secured: !include traits/auth.raml
  - barcode_id: !include traits/barcode_id.raml
  - display: !include traits/display.raml
  - email: !include traits/email.raml
  - item_id: !include traits/item_id.raml
  - language: !include traits/language.raml
  - orderable: !include traits/orderable.raml
  - pageable: !include traits/pageable.raml
  - payment: !include traits/payment.raml
  - reason: !include traits/reason.raml
  - searchable: !include traits/searchable.raml
  - time-period: !include traits/time-period.raml
