  - secured: !include auth.raml
  - barcode_id: !include barcode_id.raml
  - display: !include display.raml
  - email: !include email.raml
  - item_id: !include item_id.raml
  - language: !include language.raml
  - orderable: !include orderable.raml
  - pageable: !include pageable.raml
  - payment: !include payment.raml
  - reason: !include reason.raml
  - searchable: !include searchable.raml
  - time-period: !include time-period.raml
